"""empty message

Revision ID: 89b5b01bc471
Revises: aa67e1438685
Create Date: 2022-06-29 07:06:50.406412

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89b5b01bc471'
down_revision = 'aa67e1438685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favoritos', 'id_personaje',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('favoritos', 'id_planeta',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('favoritos', 'id_vehiculo',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favoritos', 'id_vehiculo',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('favoritos', 'id_planeta',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('favoritos', 'id_personaje',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
